name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    # container:
    #   image: uninen/node:22
    #   options: --user duser

    env:
      PLAYWRIGHT_VERSION: ""

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Get Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV

      - name: Cache playwright binaries
        uses: actions/cache@v4.1.2
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install deps
        run: |
          pnpm install --frozen-lockfile

      - run: pnpm exec playwright install-deps
      - run: pnpm exec playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Type Check
        run: pnpm ts

      #   - name: Install Playwright browsers
      #     run: pnpm exec playwright install --with-deps

      - name: Run e2e tests
        run: |
          pnpm build
          pnpm playwright test --project="mobile"

      - name: Run unit tests
        run: pnpm test:ci

      - name: Coverage
        uses: davelosert/vitest-coverage-report-action@v2.8.0
        if: ${{ always() }}
